name: maridao
version: '1.0-SNAPSHOT'
main: io.pluginteste.maridao.Maridao
api-version: '1.21'

commands:
  ola:
    description: Diz olá para o jogador.
  espadatrovao:
    description: Dá ao jogador uma Espada do Trovão.
  acessorios:
    description: Adiciona um acessorio ao jogador
    usage: /acessorios <tipoDeAcessorio>
  stomper:
    description: Botas de stomper
  kangaroo:
    description: Kit Kangaroo
  home:
    description: Teleporta o jogador para casa
  sethome:
    description: Define a casa do jogador
  superpoderosa:
    description: voce se transforma em uma menina super poderosa
  plot:
    description: Stick de plot